import type { Metadata } from "next";
import "./globals.css";
import {ReactNode} from "react";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {ThemeProvider} from "@/components/ThemeProvider";
import {Layout} from "antd";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";
import dynamic from "next/dynamic";
import {GooglePickerProvider} from "@/components/GooglePickerProvider";

const PdfjsProvider = dynamic(() => import("@/components/PdfjsProvider").then((v)=>v.PdfjsProvider), { ssr: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AntdRegistry>
          <ThemeProvider>
            <Layout className={"!min-h-screen h-screen"}>
              <Header/>
              {children}
              <Footer/>
            </Layout>
          </ThemeProvider>
          <PdfjsProvider/>
          <GooglePickerProvider/>
        </AntdRegistry>
      </body>
    </html>
  );
}

