import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {ThemeProvider} from "@/components/ThemeProvider";
import {Layout} from "antd";
import {Header} from "@/components/Header";
import {Content} from "antd/lib/layout/layout";
import {Footer} from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AntdRegistry>
          <ThemeProvider>
            <Layout className={"!min-h-screen"}>
              <Header/>
              <div className={"flex-1 flex flex-col"}>
                {children}
              </div>
              <Footer/>
            </Layout>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}

