import type { Metadata } from "next";
import {ReactNode} from "react";
import {HeaderLogo} from "@/app/(_)/_components/HeaderLogo";
import {AntContent} from "@/components/AntContent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <AntContent className={"flex flex-col"}>
      <HeaderLogo/>
      <div className={"px-8 flex-1"}>
        {children}
      </div>
    </AntContent>
  );
}

